import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { burnsAttempt } from '../core/accounting.js';
import { startedAt } from '../core/bounds.js';
import { boardRel, PROJECT_RUNS_DIR, RESULTS_DIR, RUNS_DIR } from '../core/layout.js';
import type { Log } from '../core/log.js';
import type { AgentReport } from '../core/runs.js';
import {
  isInFlight,
  isProjectRun,
  isRunId,
  needsResolution,
  parseAgentReport,
  parseRun,
  type RunRecord,
  serializeRun,
  withForgiveness,
  withoutReport,
  withReport,
  withResolution,
} from '../core/runs.js';
import { BOARDS, type BoardName } from '../core/types.js';
import { groupsOf, reapGroups } from '../server/runs/reaper.js';
import { redact } from './redaction.js';
import { writeAtomic } from './write-queue.js';

// Run records on disk.
//
// `<board>/results/<CARD-ID>/<runId>.md` inside the boards folder — beside the card, so a card's
// history travels with it in git, and invisible to the board because readBoard only reads folders
// named by configured columns.
//
// The agent never writes here. It writes its report under `RUNS_DIR` and this module folds it in,
// because the record's frontmatter is ours: agents rewrite files wholesale, and a shared file would
// lose the timings. Anything in a results folder that does not parse as a run is ignored rather
// than trusted.

function cardDir(root: string, board: BoardName, card: string): string {
  return join(root, boardRel(board, RESULTS_DIR, card));
}

// The backstop, not the message. Both stores build a path by interpolating a run id that reached the
// server as a URL segment, so the shape is checked at the point of use as well as at the route: a
// route can be added without its author knowing this, and the reviewer who found the hole found it in
// the one route that had no check. Throwing rather than returning undefined because there is no
// legitimate caller — every id here was either generated by `runId` or already refused upstream.
function pathIn(dir: string, run: string): string {
  if (!isRunId(run)) throw new Error(`not a run id: ${JSON.stringify(run)}`);
  return join(dir, `${run}.md`);
}

export function recordPath(root: string, board: BoardName, card: string, run: string): string {
  return pathIn(cardDir(root, board, card), run);
}

// A project run's home. One level up from the card store and named for what it holds, so a checkup's
// record is somewhere a person would think to look.
export function projectRunPath(root: string, run: string): string {
  return pathIn(join(root, PROJECT_RUNS_DIR), run);
}

// Which of the two stores this record belongs in. Derived from the record rather than passed in, so
// there is no way for a caller to file one in the wrong place.
function pathFor(root: string, record: RunRecord): string {
  return isProjectRun(record)
    ? projectRunPath(root, record.run)
    : recordPath(root, record.board as BoardName, record.card as string, record.run);
}

// Where the agent is told to write. Under the runs folder so a chatty agent does not churn the
// board watcher, and so a half-written report never sits in a card's folder.
export function reportPath(root: string, run: string): string {
  return join(root, RUNS_DIR, `${run}.report.md`);
}

function transcriptPath(root: string, run: string): string {
  return join(root, RUNS_DIR, `${run}.log.jsonl`);
}

// Written through a rename, which is atomic within a directory, so a reader sees either the previous
// record or the new one and never a half-written file. `writeFile` truncates before it writes, and
// these files are read constantly while they are being written — by the watcher, by GET /runs, and by
// a second write to the same record moments later. Found when recording a run's process group added
// that second write and an immediate read came back as "not a run at all".
//
// `writeAtomic` rather than an inline copy of it, which is what this used to be. The two requirements
// this store places on it are both properties that copy already had, and both are now pinned by a test
// (test/atomic-write.test.ts) so that the shared one cannot lose them for the callers that never
// noticed they depended on them:
//
//   - THE TEMPORARY NAME MUST NOT END IN `.md`. The listers below filter on that extension, so an
//     interrupted write must leave something that is ignored rather than something that half-parses.
//     A crash between the write and the rename also leaves the temp file behind for ever, inside a
//     directory that is committed to git — and because nothing lists it, nobody ever notices.
//   - IT MUST BE UNIQUE PER WRITE, not per record. Two writes of the same record do overlap in
//     practice (the queue marking a run `running` and the spawn recording its process group, moments
//     apart and neither awaited by the other), and a shared temp name made them race for it: one
//     rename found the file already gone, so that write silently did nothing. It cost a missing
//     `running` update in the dashboard.
export function writeRun(root: string, record: RunRecord): Promise<void> {
  return writeAtomic(pathFor(root, record), serializeRun(record));
}

export async function readRun(
  root: string,
  board: BoardName,
  card: string,
  run: string,
): Promise<RunRecord | null> {
  try {
    return parseRun(await readFile(recordPath(root, board, card, run), 'utf8'));
  } catch {
    return null;
  }
}

// Every run file in one folder, oldest first. Ids are sortable stamps, so the filename order IS
// chronological order and no file needs opening to sort. Anything that does not parse as a run is
// skipped: a results folder is ordinary disk, and a stray note must not become a phantom run.
async function runsInDir(dir: string): Promise<RunRecord[]> {
  let files: string[];
  try {
    files = (await readdir(dir)).filter((f) => f.endsWith('.md')).sort();
  } catch {
    return [];
  }
  const runs: RunRecord[] = [];
  for (const file of files) {
    try {
      const record = parseRun(await readFile(join(dir, file), 'utf8'));
      if (record) runs.push(record);
    } catch {
      /* vanished between readdir and read */
    }
  }
  return runs;
}

// Every run for one card, oldest first.
export async function listCardRuns(root: string, board: BoardName, card: string): Promise<RunRecord[]> {
  return runsInDir(cardDir(root, board, card));
}

// Every project-level run — the checkups and pre-flights — oldest first.
export async function listProjectRuns(root: string): Promise<RunRecord[]> {
  return runsInDir(join(root, PROJECT_RUNS_DIR));
}

export async function readProjectRun(root: string, run: string): Promise<RunRecord | null> {
  try {
    return parseRun(await readFile(projectRunPath(root, run), 'utf8'));
  } catch {
    return null;
  }
}

// Every run in the project, newest first — the Execution dashboard's list, and what spend is summed
// from. Reads BOTH stores: each board's results folders and the project-level one. That is the whole
// cost of giving project runs a home of their own.
//
// NEWEST BY `started`, WITH THE ID AS THE TIE-BREAK, and not by the id alone, which is what this was. A run
// id is the timestamp to the SECOND plus a random four-character suffix (server/app.ts), so two runs in the
// same second sorted on a coin flip. Nothing was broken by it — every consumer of this list is
// order-insensitive today — and it is fixed anyway because it is the same latent bug that made `bounds.ts`
// answer with the wrong work run in half the end-to-end trace's runs, and there it decided whether a task
// whose gates failed once could ever pass.
export async function listRuns(root: string): Promise<RunRecord[]> {
  const all: RunRecord[] = await listProjectRuns(root);
  for (const board of BOARDS) {
    let cards: string[];
    try {
      cards = (await readdir(join(root, boardRel(board, RESULTS_DIR)), { withFileTypes: true }))
        .filter((e) => e.isDirectory())
        .map((e) => e.name);
    } catch {
      continue; // this board has never had a run
    }
    for (const card of cards) all.push(...(await listCardRuns(root, board, card)));
  }
  return all.sort((a, b) => startedAt(b) - startedAt(a) || b.run.localeCompare(a.run));
}

// Read and consume the agent's report. Consumed so a later run cannot pick up an earlier one's
// file, which would attach the wrong outcome to the wrong run.
export async function takeAgentReport(root: string, run: string): Promise<string | null> {
  const path = reportPath(root, run);
  try {
    const content = await readFile(path, 'utf8');
    await rm(path, { force: true });
    return content;
  } catch {
    return null;
  }
}

export async function appendTranscript(root: string, run: string, line: string): Promise<void> {
  const path = transcriptPath(root, run);
  await mkdir(join(path, '..'), { recursive: true });
  await writeFile(path, `${line}\n`, { encoding: 'utf8', flag: 'a' });
}

// The last few lines of a transcript, for a run that ended without a report. Something to show
// beats an empty pane when the question is "what did it actually do".
export async function transcriptTail(root: string, run: string, lines = 40): Promise<string> {
  try {
    const content = await readFile(transcriptPath(root, run), 'utf8');
    return content.trim().split('\n').slice(-lines).join('\n');
  } catch {
    return '';
  }
}

export function reportContract(run: string): string {
  return `${RUNS_DIR}/${run}.report.md`;
}

// Records still claiming to be queued or running when the project opens: their child processes died
// with the server that spawned them, so they are stale, not live. Marked interrupted so the
// dashboard never shows a run that will never finish.
// `live` is the runs this process still has in flight, and they are skipped. Without it, reopening
// a project while a run is going rewrites that run to `interrupted` — a status the record then keeps
// even as the agent finishes and writes its report, and one that burns no attempt.
export async function markInterrupted(root: string, at: string, live: string[] = []): Promise<number> {
  const running = new Set(live);
  const stale = (await listRuns(root)).filter((r) => isInFlight(r.status) && !running.has(r.run));
  // Decision 13: reaping belongs on this path, because this is where "the server that spawned it is
  // gone" is already established. A record's children USUALLY died with that server; when they did
  // not, this record is the only account of what to kill, and each group is identified before it is
  // signalled — see reaper.ts.
  reapGroups(groupsOf(stale));
  for (const record of stale) {
    await writeRun(
      root,
      withoutReport(record, 'interrupted', 'VibeBoard restarted while this run was in flight', at),
    );
  }
  return stale.length;
}

// Mark one run dealt with. Returns the record either way: resolving one twice, or resolving a run
// that was never asking, is a no-op rather than an error — the dashboard and the card both offer the
// action, and two clicks must not mean two writes.
export async function resolveRun(
  root: string,
  board: BoardName,
  card: string,
  run: string,
  at: string,
): Promise<RunRecord | null> {
  const record = await readRun(root, board, card, run);
  if (!record) return null;
  if (!needsResolution(record)) return record;
  const resolved = withResolution(record, at);
  await writeRun(root, resolved);
  return resolved;
}

// The same, for a run with no card in its path to find it by. A failed checkup would otherwise sit
// in the dashboard's attention group forever: the card route needs a board and a card, and this run
// has neither.
export async function resolveProjectRun(root: string, run: string, at: string): Promise<RunRecord | null> {
  const record = await readProjectRun(root, run);
  if (!record) return null;
  if (!needsResolution(record)) return record;
  const resolved = withResolution(record, at);
  await writeRun(root, resolved);
  return resolved;
}

// Every unresolved run on one card, dealt with at once — what closing the card means. Returns how
// many were written, so a caller can tell "nothing was waiting" from "three were".
export async function resolveCardRuns(
  root: string,
  board: BoardName,
  card: string,
  at: string,
): Promise<number> {
  const pending = (await listCardRuns(root, board, card)).filter(needsResolution);
  for (const record of pending) await writeRun(root, withResolution(record, at));
  return pending.length;
}

// Every attempt this card has spent, cleared, so auto-pilot will dispatch it again. Returns how many
// records were stamped, so a caller can say "there was nothing to clear" rather than implying it
// fixed something.
//
// WHY THERE IS NOTHING TO RESET. Attempts are DERIVED by counting run records (core/accounting.ts) —
// there is no counter anywhere — so a card that reached the cap stayed at the cap for ever, and the
// only way out was to move its result files out of the folder by hand. That destroys the account of
// why the card was blocked, which is the one thing worth keeping, and no user could be expected to
// know to do it. Measured 2026-08-15: a dead credential failed three runs of P-011 in 58ms each, the
// cap was reached, and auto-pilot stopped for good.
//
// So this STAMPS. Nothing is deleted and nothing else about a record is rewritten — the history is
// the point, and a forgiven run still reads as the failure it was.
//
// FILTERED ON `burnsAttempt` rather than on a status list, which is what makes it exact in two
// directions at once. A cancelled or interrupted run costs the card nothing already, so stamping it
// would be a write recording a decision nobody had to take; and an already-forgiven run does not burn
// either, so a second click cannot rewrite the timestamp the first one wrote.
export async function forgiveCardRuns(
  root: string,
  board: BoardName,
  card: string,
  at: string,
): Promise<number> {
  // A STRIKE, NOT MERELY A BURN — and the difference is a success.
  //
  // `burnsAttempt` alone was the obvious filter and it is wrong. Measured against the real poisoned
  // card, P-011 in tic-tac-toe: three failed `checkup-story` runs, which are what the user is clearing,
  // and one `break-down` from hours earlier that SUCCEEDED and produced E-013. Forgiving on `burnsAttempt`
  // cleared all four, taking `attemptsUsed(runs, 'P-011', 'break-down')` to zero — so the loop would have
  // been free to break the card down a second time and hang another set of children off it.
  //
  // `BURNS.success` is true for a reason accounting.ts states (a card dragged back into a routed column
  // really has had a run of that skill), and nothing here should undo it. The user is clearing failures;
  // a run that worked is history, not a strike against the card.
  const spent = (await listCardRuns(root, board, card)).filter(
    (r) => burnsAttempt(r) && r.status !== 'success',
  );
  for (const record of spent) await writeRun(root, withForgiveness(record, at));
  return spent.length;
}

// THE ONE THAT CLEARS A SUCCESS (decision 86), and it is a second function rather than a flag on the first
// because the two are different decisions with different costs.
//
// `forgiveCardRuns` above spares a success deliberately, and that restraint is right for what it is for:
// the user is clearing failures, and clearing a `break-down` that WORKED frees the loop to break the card
// down again and hang a second set of children off it.
//
// But a card can be stopped by its successes alone, and then that button clears nothing at all. Measured on
// F-003: every story done, the feature checkup run four times — three `success` and one `attention` already
// forgiven — so the card sat at three of three attempts with every remaining record a success, and the
// product offered no route back. A state a person cannot get out of is worse than a remedy with a cost, so
// long as the cost is stated: the confirmation on this one says plainly that a cleared creating run lets the
// loop create children again.
//
// FILTERED ON `burnsAttempt` ALONE, which is exactly the difference. Everything else it excludes still
// applies and for the same reasons — a cancelled or interrupted run costs the card nothing, an in-flight one
// has not ended, a classified fault is not the card's doing, and an already-forgiven record must not have
// its timestamp rewritten by a second click.
//
// STAMPS, deletes nothing, like every other way out of a spent card: the history is the point, and a run
// cleared this way still reads as the success it was.
export async function resetCardRuns(
  root: string,
  board: BoardName,
  card: string,
  at: string,
): Promise<number> {
  const spent = (await listCardRuns(root, board, card)).filter(burnsAttempt);
  for (const record of spent) await writeRun(root, withForgiveness(record, at));
  return spent.length;
}

// THE SAME WAY OUT FOR THE POSITION THAT HAS NO CARD.
//
// An empty board plus a README is derived by a CARD-LESS run of the bootstrap skill, and its cap is counted
// over project runs of that skill (`bootstrap`, core/lifecycle/tick.ts) — `attemptsUsed` counts per card and
// a project run has none, so that tally is the only one there is. `forgiveCardRuns` needs a board and a card
// to locate records at all, so a bootstrap the machine had spent had no supported way back at all.
//
// Measured 2026-08-16: the calculator's three derivation attempts were consumed by an OpenCode server that
// could not be reached — 449ms each, no model, no tokens — and auto-pilot stopped saying the README might be
// too thin. Clearing them meant moving files out of `project-runs/` by hand, which is both undiscoverable
// and destructive of the only account of why the project was stuck.
//
// STOPS AT THE PROJECT'S OWN RUNS, deliberately. Clearing a stuck derivation must not quietly re-open every
// card in the project: those are a different position with a button of their own.
export async function forgiveProjectRuns(root: string, at: string): Promise<number> {
  // Same filter as the card version and for the same two reasons: `burnsAttempt` excludes what never cost
  // anything (cancelled, interrupted, in flight, already infrastructure, already forgiven), so a second
  // click cannot restamp; and `!== 'success'` keeps a derivation that WORKED, because forgiving it would
  // let the loop derive the whole board a second time.
  const spent = (await listProjectRuns(root)).filter((r) => burnsAttempt(r) && r.status !== 'success');
  for (const record of spent) await writeRun(root, withForgiveness(record, at));
  return spent.length;
}

// Has this card already had one? The lookup only happens for a report we could not read, which is rare,
// so it costs a readdir on exactly the runs that were going to be written to anyway.
//
// `forgiven` runs do not count. A person clearing a card's attempts is saying the history is dealt with,
// and leaving a forgiven record here would make the very next unreadable report burn — which is the
// override quietly failing to override.
async function hadUnreadableReport(root: string, record: RunRecord): Promise<boolean> {
  const previous = isProjectRun(record)
    ? await listProjectRuns(root)
    : await listCardRuns(root, record.board as BoardName, record.card as string);
  return previous.some((r) => r.run !== record.run && r.fault === 'unreadable-report' && !r.forgiven);
}

// DECISION 10, ANSWERED BY THE FILE RATHER THAN BY A MOUNT.
//
// The original deferral said AppArmor could not express per-run report exclusivity and named Landlock as
// the fix. Containment is Docker now and a single-file mount IS possible — so this was re-decided on
// 2026-09-01 rather than inherited, and the mount is still the expensive answer. Asking the report which
// run it belongs to costs nothing, needs no kernel feature, and catches what a mount would not: a hung
// run whose report lands after the server has moved on, and a report copied from a previous run.
//
// WHAT IT IS AND IS NOT. This is an accident check, not a security control — an agent writes the file,
// so an agent could write the matching id too. What it defends against is confusion: the wrong path, a
// stale file, a template carried over. `reportPath` already puts the run id in the FILENAME, so the two
// together mean a report has to be wrong twice before it is believed.
//
// Absent is accepted: reports written before this field existed have none, and the on-disk format is
// frozen. Only a mismatch is refused.
function checkReportIdentity(report: AgentReport, run: string): AgentReport {
  if (report.run === undefined || report.run === run) return report;
  return {
    ...report,
    // EVERY DECISION IN IT IS DISCARDED, not only the verdict — corrected in review, where dropping the
    // verdict alone turned out to leave `outcome: success` intact. A foreign report was therefore written
    // to disk as a SUCCESSFUL run carrying another run's summary and body, and `created:` brought another
    // run's card ids with it, which is the loop being told about cards this run never made.
    //
    // `attention` and not `failed`: nothing here says the work failed, only that we cannot tell whose
    // work it was. That is the same reasoning S1 applies to a run the user stopped — the report is kept
    // as EVIDENCE and its verdict is ours to withhold.
    outcome: 'attention' as const,
    verdict: undefined,
    created: undefined,
    unreadable: `it declares run ${report.run}, and this is run ${run}`,
  };
}

// Fold a finished agent report into the record. Returns the updated record, or null when the agent
// wrote nothing — the caller decides what a report-less run means.
// `secret` is the run's credential, redacted out of the report before it is folded in. The report
// becomes part of the run record, which is written to disk and broadcast over the websocket — so an
// agent that quotes its own token there was persisting it, and `expireRun` fires after this, so the
// value is live at the moment it is written and dead but permanent afterwards. The transcript was
// already covered; this is the same leak through the other channel.
//
// `log` is optional and is how the unreadable case reaches a person before anyone reads the record. It
// is the port from `core/log.ts`, so this stays a store module: it takes a logger, it does not know
// what writes the log.
export async function foldReport(
  root: string,
  record: RunRecord,
  finished: string,
  secret?: string,
  log?: Log,
): Promise<RunRecord | null> {
  const raw = await takeAgentReport(root, record.run);
  if (raw === null) return null;
  const content = redact(raw, secret);
  const parsed = checkReportIdentity(parseAgentReport(content), record.run);
  // FREE ONCE, THEN IT BURNS. Asked here rather than derived at read time because `fault` is a stored
  // classification of how a run ended — the same field `neverReachedModel` writes — and every counter
  // already reads it from the record. Deriving this one instead would mean giving `burnsAttempt` the
  // whole history, which is four call sites and a different shape of function for one clause.
  const repeat = parsed.unreadable !== undefined && (await hadUnreadableReport(root, record));
  const report = repeat ? { ...parsed, repeat: true as const } : parsed;
  if (report.unreadable !== undefined) {
    log?.warn(
      { run: record.run, card: record.card, reason: report.unreadable, charged: repeat },
      repeat
        ? 'a report the server could not read, and not the first on this card — the run is charged'
        : 'a report the server could not read — the run is recorded and the card is not charged for it',
    );
  }
  const folded = withReport(record, report, finished);
  await writeRun(root, folded);
  return folded;
}
